return {
  { "mason-org/mason.nvim", event = "VeryLazy", cmd = "Mason", build = ":MasonUpdate" },
  {
    "mason-org/mason-lspconfig.nvim",
    event = "VeryLazy",
    dependencies = { "mason-org/mason.nvim", "neovim/nvim-lspconfig" },
  },
  {
    "WhoIsSethDaniel/mason-tool-installer.nvim",
    event = "VeryLazy",
    dependencies = { "mason-org/mason.nvim" },
    opts = {
      ensure_installed = {
        "bash-language-server",
        "black",
        "diagnostic-languageserver",
        "dockerfile-language-server",
        "editorconfig-checker",
        "efm",
        "eslint-lsp",
        "eslint_d",
        "jq",
        "js-debug-adapter",
        "json-lsp",
        "lua-language-server",
        "markdownlint",
        "markdownlint-cli2",
        "marksman",
        "prettier",
        "prettierd",
        "python-lsp-server",
        "ruff",
        "shellcheck",
        "shfmt",
        "stylua",
        "typescript-language-server",
        "vim-language-server",
        "vint",
        "xmlformatter",
        "yaml-language-server",
        "yamllint",
      },
      auto_update = false,
      run_on_start = true,
      start_delay = 1000,
    },
  },
  { "bullets-vim/bullets.vim", event = "VeryLazy", ft = { "markdown", "text" } },
}
