require("mason").setup({ ui = { border = "single" } })

require("mason-tool-installer").setup({
	ensure_installed = {
		"bash-language-server",
		"black",
		"diagnostic-languageserver",
		"dockerfile-language-server",
		"editorconfig-checker",
		"efm",
		"eslint-lsp",
		"eslint_d",
		"jq",
		"js-debug-adapter",
		"json-lsp",
		"lua-language-server",
		"markdownlint",
		"markdownlint-cli2",
		"marksman",
		"prettier",
		"prettierd",
		"python-lsp-server",
		"ruff",
		"shellcheck",
		"shfmt",
		"stylua",
		"typescript-language-server",
		"vim-language-server",
		"vint",
		"xmlformatter",
		"yaml-language-server",
		"yamllint",
	},
	auto_update = false,
	run_on_start = true,
	start_delay = 1000,
})
