-----------------------------------------------------------
-- Импорт модулей lua
-----------------------------------------------------------
require("plugins-setup")
require("auto_dark_mode")
require("core.colorscheme")
require("core.diagnostic")
require("core.keymaps")
require("core.options")
require("core.settings")
require("plugins.bufferline")
require("plugins.gitsigns")
require("plugins.indent_blankline")
require("plugins.lsp.config")
require("plugins.lsp.mason")
require("plugins.lsp.options")
require("plugins.lualine")
require("plugins.neogit")
require("plugins.neotest")
-- require("plugins.nvim-cmp")
require("plugins.blink")
require("plugins.nvim-tree")
require("plugins.obsidian")
require("plugins.others")
